# Generated by Django 3.2.16 on 2023-01-24 11:18

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contractors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Название')),
                ('color', colorfield.fields.ColorField(blank=True, default='#FFFFE0', image_field=None, max_length=7, null=True, samples=None, unique=True, verbose_name='Цвет в HEX')),
                ('slug', models.SlugField(max_length=10, unique=True, verbose_name='Уникальный ключ')),
            ],
            options={
                'verbose_name': 'Заказчик',
                'verbose_name_plural': 'Заказчик',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Well',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field', models.CharField(max_length=200, unique=True, verbose_name='Месторождение')),
                ('rig', models.CharField(max_length=10, verbose_name='Куст')),
                ('well_number', models.CharField(blank=True, max_length=10, verbose_name='Описание рецепта')),
                ('status', models.CharField(choices=[('В бурении', 'В бурении'), ('В ожидании', 'В ожидании'), ('Добурена', 'Добурена')], max_length=20, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='contractors.contractor', verbose_name='Подрядчик')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wells', to='customers.customer', verbose_name='Заказчик')),
            ],
            options={
                'verbose_name': 'Скважина',
                'verbose_name_plural': 'Скважины',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='well',
            constraint=models.UniqueConstraint(fields=('customer', 'field'), name='unique_customers_field'),
        ),
    ]
