# Generated by Django 3.2.16 on 2023-01-25 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='well_number',
            field=models.CharField(blank=True, max_length=10, verbose_name='Скважина'),
        ),
    ]
