# Generated by Django 4.1.5 on 2023-01-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_well_well_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='rig',
            field=models.CharField(blank=True, max_length=10, verbose_name='Куст'),
        ),
        migrations.AlterField(
            model_name='well',
            name='well_number',
            field=models.CharField(max_length=10, verbose_name='Скважина'),
        ),
    ]
