# Generated by Django 4.1.5 on 2023-03-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_well_rig_alter_well_well_number'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='well',
            name='unique_customers_field',
        ),
        migrations.AddConstraint(
            model_name='well',
            constraint=models.UniqueConstraint(fields=('field', 'rig', 'well_number'), name='unique_field_well'),
        ),
    ]
