# Generated by Django 4.1.5 on 2023-03-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_remove_well_unique_customers_field_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='well',
            name='unique_field_well',
        ),
        migrations.AddConstraint(
            model_name='well',
            constraint=models.UniqueConstraint(fields=('rig', 'well_number'), name='unique_field_well'),
        ),
    ]
