# Generated by Django 4.1.5 on 2023-03-23 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0006_remove_well_unique_field_well_well_unique_rig_well'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='well',
            name='unique_rig_well',
        ),
        migrations.AlterField(
            model_name='well',
            name='field',
            field=models.CharField(max_length=200, verbose_name='Месторождение'),
        ),
        migrations.AddConstraint(
            model_name='well',
            constraint=models.UniqueConstraint(fields=('field', 'rig', 'well_number'), name='unique_rig_well'),
        ),
    ]
