# Generated by Django 4.1.5 on 2023-03-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_remove_well_unique_rig_well_alter_well_field_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='correction_value',
            field=models.FloatField(blank=True, null=True, verbose_name='SAG'),
        ),
        migrations.AddField(
            model_name='well',
            name='current_correction',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Текущая коррекция'),
        ),
        migrations.AddField(
            model_name='well',
            name='current_depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Текущая глубина'),
        ),
        migrations.AddField(
            model_name='well',
            name='north',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Привязка к северу'),
        ),
        migrations.AddField(
            model_name='well',
            name='plan_depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Плановая глубина'),
        ),
        migrations.AddField(
            model_name='well',
            name='sag',
            field=models.FloatField(blank=True, null=True, verbose_name='SAG'),
        ),
        migrations.AddField(
            model_name='well',
            name='start_date',
            field=models.DateField(blank=True, max_length=10, null=True, verbose_name='Дата начала сопровождения'),
        ),
        migrations.AddField(
            model_name='well',
            name='start_depth',
            field=models.IntegerField(blank=True, null=True, verbose_name='Начальная глубина'),
        ),
        migrations.AddField(
            model_name='well',
            name='telesystem',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Телесистема'),
        ),
        migrations.AddField(
            model_name='well',
            name='telesystem_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Номер телесистемы'),
        ),
    ]
