# Generated by Django 4.1.5 on 2023-03-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_well_correction_value_well_current_correction_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='well',
            name='EX',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NX'),
        ),
        migrations.AddField(
            model_name='well',
            name='NY',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='NY'),
        ),
        migrations.AddField(
            model_name='well',
            name='amplitude',
            field=models.IntegerField(blank=True, null=True, verbose_name='Амплитуда точки отсчета'),
        ),
        migrations.AddField(
            model_name='well',
            name='btotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Btotal'),
        ),
        migrations.AddField(
            model_name='well',
            name='critical_azimuth',
            field=models.BooleanField(blank=True, null=True, verbose_name='Критический азимут'),
        ),
        migrations.AddField(
            model_name='well',
            name='dip',
            field=models.FloatField(blank=True, null=True, verbose_name='Dip'),
        ),
        migrations.AddField(
            model_name='well',
            name='geomagnetic_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата геомагнитная модель'),
        ),
        migrations.AddField(
            model_name='well',
            name='geomagnetic_model',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Геомагнитная модель'),
        ),
        migrations.AddField(
            model_name='well',
            name='gtotal',
            field=models.FloatField(blank=True, null=True, verbose_name='Gtotal'),
        ),
        migrations.AddField(
            model_name='well',
            name='latitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Широта'),
        ),
        migrations.AddField(
            model_name='well',
            name='longtitude',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Долгота'),
        ),
        migrations.AddField(
            model_name='well',
            name='magn',
            field=models.FloatField(blank=True, null=True, verbose_name='Магнитное склонение'),
        ),
        migrations.AddField(
            model_name='well',
            name='meridian',
            field=models.FloatField(blank=True, null=True, verbose_name='Угол схождения меридианов'),
        ),
        migrations.AddField(
            model_name='well',
            name='north_direction',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Направление на север'),
        ),
        migrations.AlterField(
            model_name='well',
            name='correction_value',
            field=models.FloatField(blank=True, null=True, verbose_name='Значение поправки'),
        ),
        migrations.AlterField(
            model_name='well',
            name='current_correction',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Система координат'),
        ),
    ]
