export const ADD_NEW_CONTRACTOR_REQUEST: "ADD_NEW_CONTRACTOR_REQUEST" =
  "ADD_NEW_CONTRACTOR_REQUEST";
export const ADD_NEW_CONTRACTOR_SUCCESS: "ADD_NEW_CONTRACTOR_SUCCESS" =
  "ADD_NEW_CONTRACTOR_SUCCESS";
export const ADD_NEW_CONTRACTOR_FAILED: "ADD_NEW_CONTRACTOR_FAILED" =
  "ADD_NEW_CONTRACTOR_FAILED";
export const GET_ALL_CONTRACTORS_REQUEST: "GET_ALL_CONTRACTORS_REQUEST" =
  "GET_ALL_CONTRACTORS_REQUEST";
export const GET_ALL_CONTRACTORS_SUCCESS: "GET_ALL_CONTRACTORS_SUCCESS" =
  "GET_ALL_CONTRACTORS_SUCCESS";
export const GET_ALL_CONTRACTORS_FAILED: "GET_ALL_CONTRACTORS_FAILED" =
  "GET_ALL_CONTRACTORS_FAILED";
export const DELETE_CONTRACTOR_REQUEST: "DELETE_CONTRACTOR_REQUEST" =
  "DELETE_CONTRACTOR_REQUEST";
export const DELETE_CONTRACTOR_SUCCESS: "DELETE_CONTRACTOR_SUCCESS" =
  "DELETE_CONTRACTOR_SUCCESS";
export const DELETE_CONTRACTOR_FAILED: "DELETE_CONTRACTOR_FAILED" =
  "DELETE_CONTRACTOR_FAILED";
