export const ADD_NEW_WELL_REQUEST: 'ADD_NEW_WELL_REQUEST' =
  'ADD_NEW_WELL_REQUEST'
export const ADD_NEW_WELL_SUCCESS: 'ADD_NEW_WELL_SUCCESS' =
  'ADD_NEW_WELL_SUCCESS'
export const ADD_NEW_WELL_FAILED: 'ADD_NEW_WELL_FAILED' = 'ADD_NEW_WELL_FAILED'
export const GET_ALL_WELLS_REQUEST: 'GET_ALL_WELLS_REQUEST' =
  'GET_ALL_WELLS_REQUEST'
export const GET_ALL_WELLS_SUCCESS: 'GET_ALL_WELLS_SUCCESS' =
  'GET_ALL_WELLS_SUCCESS'
export const GET_ALL_WELLS_FAILED: 'GET_ALL_WELLS_FAILED' =
  'GET_ALL_WELLS_FAILED'
