# Generated by Django 3.2.16 on 2023-01-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.EmailField(max_length=50, unique=True, verbose_name='Почта')),
                ('phone', models.CharField(max_length=7, unique=True, verbose_name='Телефон')),
            ],
            options={
                'verbose_name': 'Подрядчик',
                'verbose_name_plural': 'Подрядчики',
                'ordering': ['name'],
            },
        ),
    ]
