# Generated by Django 3.2.16 on 2023-01-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='email',
            field=models.EmailField(default=1, max_length=50, unique=True, verbose_name='Почта'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contractor',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Название'),
        ),
    ]
