# Generated by Django 3.2.16 on 2023-01-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractors', '0002_auto_20230124_1420'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractor',
            name='phone',
            field=models.CharField(max_length=10, unique=True, verbose_name='Телефон'),
        ),
    ]
